"""init users table

Revision ID: e94fa7a9d7d2
Revises: 
Create Date: 2026-04-20 00:08:21.622474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e94fa7a9d7d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_pokemon')
    op.drop_index('ix_teams_user_id', table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_teams_user_id', 'teams', ['user_id'], unique=False)
    op.create_table('team_pokemon',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pokemon_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('type2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('slot', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_pokemon_team_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='team_pokemon_pkey')
    )
    # ### end Alembic commands ###